title : Davide's place
tagline : Development, Design, Photography and Life
url : http://davide.im

author :
  name : Davide Taviani
  email : info@davidetaviani.com
  url : http://davide.im
  facebook: davide.taviani
  gplus: 106885346251122953844
  twitter : helios
  linkedin: davidetaviani
  github : heliosmaster

paginate: 5
pygments : true
markdown: rdiscount
baseurl :
permalink: /:title/
relative_permalinks : true
